In [45]:
import os
import librosa
import numpy as np

from pprint import pprint

Alguns dos áudios disponíveis tem tamanhos diferentes. Vou filtrar apenas alguns para realizar experimentos

In [46]:
audio_folder_path = '../../data/huang/Segmented/'

In [47]:
l = list()

for filepath, _, filenames in os.walk(audio_folder_path):
    for filename in filenames:
        audio_file = os.path.join(filepath, filename)
        l.append(librosa.load(audio_file, sr=None))

In [48]:
from collections import defaultdict
d = defaultdict(int)

for i in range(len(l)):
    d[len(l[i][0])] += 1

In [49]:
pprint(d.items())
most_common_length = max(d.items(), key=lambda x: x[1])
print("Valor mais comum: ", most_common_length)

dict_items([(177152, 1998), (176128, 5513), (77824, 1), (25600, 1), (2048, 1), (90112, 1), (32768, 1), (64512, 1), (43008, 1), (75776, 1)])
Valor mais comum:  (176128, 5513)


In [50]:
l = None

Sabendo que o tamanho mais comum é 176128 e o segundo mais comum é 177152, vou usar o segundo mais comum para facilitar com a memória.

In [51]:
def filter_length(datapath, length):
    l = []
    for filepath, _, filenames in os.walk(audio_folder_path):
        for filename in filenames:
            audio_file = os.path.join(filepath, filename)
            audio_data = librosa.load(audio_file, sr=None)
            if len(audio_data[0]) == length:
                l.append(audio_file)
    return l

In [52]:
most_common = 176128
second_most_common = 177152
filtered_files = filter_length(audio_folder_path, second_most_common)

In [53]:
filtered_files[:3]

['../../data/huang/Segmented/Flute1-000.wav',
 '../../data/huang/Segmented/Flute1-003.wav',
 '../../data/huang/Segmented/Flute1-007.wav']

Para carregar a lista de dados filtrados vou fazer um arquivo contendo todos os arquivos que são de mesmo tamanho.

In [54]:
most_common_name = "most_common.txt"
second_most_common_name = "second_most_common.txt"

filter_path = '../../filters/huang/'

In [56]:
filename = os.path.join(filter_path, second_most_common_name)

with open(filename, 'w') as f:
    for file in filtered_files:
        f.write(file + '\n')